apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: development
spec:
  selector:
    app: flask-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000