name: Deploy Flask App to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # Step 4: Run unit tests using pytest
      - name: Run tests with pytest
        run: pytest

      # Step 5: Login to Azure CLI using credentials from secrets
      - name: Login to Azure
        if: success()
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 6: Build Docker image and push to Docker Hub
      - name: Build and Push Docker Image to Docker Hub
        if: success()
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          IMAGE_URI=${{ secrets.DOCKERHUB_USERNAME }}/flask_app_asgmt:$TIMESTAMP
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

          docker build -t $IMAGE_URI .
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push $IMAGE_URI

      # Step 7: Configure kubectl to connect to AKS
      - name: Set up kubectl
        if: success()
        run: |
          az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

      # Step 8: Update deployment.yaml with the new Docker image URI
      - name: Update Deployment Image
        if: success()
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/flask_app_asgmt:${{ env.TIMESTAMP }}|g" deployment.yaml

      # Step 9: Deploy the updated deployment.yaml to AKS
      - name: Deploy to AKS
        if: success()
        run: |
          kubectl apply -f deployment.yaml
